name: notes
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_runner: ^2.4.9
  dart_frog: ^1.0.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_serializable: ^6.8.0
  uuid: ^4.4.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
